### ISSUE TITLE
Initialize LND wallet from existing key data

### ISSUE THREAD

**Issue by davgordo** [kiln-fired/kiln-operator#31]
When there is existing master key data available, initialize a wallet for the LND container to use.

The heavy lifting seems to be already completed if we consider [use case 1](https://github.com/lightninglabs/lndinit#example-use-case-1-basic-setup) in `lndinit`. This could be accomplished by mounting the resulting secret from a reconciled `ChainKey` and running something like the following command as an init container:

```shell
lndinit -v init-wallet \
    --secret-source=file \
    --file.seed=/safe/location/seed.txt \
    --file.wallet-password=/safe/location/walletpassword.txt \
    --init-file.output-wallet-dir=$HOME/.lnd/data/chain/bitcoin/mainnet \
    --init-file.validate-password
```

**Comment by davgordo** [comment]
Note the main LND process will need to go back and read the wallet password, so to work with the above example, we would add a flag: `--wallet-unlock-password-file=/safe/location/walletpassword.txt`

**Comment by thinkmassive** [comment]
When the wallet secret is already populated, the `lnd` pod can use the `lndinit` image with the example script as its entrypoint. The example Deployment (in [use case 2](https://github.com/lightninglabs/lndinit#example-use-case-2-kubernetes)) is missing a volumeMount for mounting `example-init-wallet-k8s.sh` at `/init-wallet-k8s.sh` (from a ConfigMap, or a custom image), but with that it should work as is (tweaking env vars for your secret names and mount points).

`lndinit store-secret` will only overwrite an existing secret if the `--overwrite` option is included. In the example script, only the RPC secret has this, which is why it's safe to always run at `lnd` startup.

For your wallet initialization purposes, once the wallet+password secrets exist you could run [these 3 commands](https://github.com/lightninglabs/lndinit/blob/14cc069/example-init-wallet-k8s.sh#L39-L63) as the startup script for the `lnd` container. Other than those, you probably want the env vars at the beginning, and the last line (`exec lnd`). This should be simpler than adding an initContainer. If you need one anyway, I suppose the fifo could be shared between containers but I haven't tested that.
